import Head from "next/head";
import Image from "next/image";
import Hero from "../components/Hero";
import Navbar from "../components/Navbar";
import Product from "../components/Product";
// import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div>
			<Head>
				<title>React commerce - home</title>
				<meta name="description" content="Generated by React commerce" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<Hero />
				<Product />
			</main>

			<footer></footer>
		</div>
	);
}
