import Head from "next/head";
import Image from "next/image";
// import styles from "../styles/Home.module.css";

export default function Home() {
	return (
		<div>
			<Head>
				<title>React commerce</title>
				<meta name="description" content="Generated by React commerce" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main>
				<h1 className="text-6xl font-bold underline">Hello world!</h1>
			</main>

			<footer></footer>
		</div>
	);
}
